import * as THREE from 'three';
import { GLTFExporter } from 'three/examples/jsm/exporters/GLTFExporter.js';

/** Generate a self-contained Three.js factory module (image embedded as data URL). */
export function factoryTS(opts: {
  dataURL: string;
  avgColor: [number, number, number];
  roughness: number;
  depth: number;
}): string {
  const c = opts.avgColor.map((n) => Math.round(n));
  return `import * as THREE from 'three';

// Auto-generated by img2threejs-web. The source image is embedded below.
const IMAGE_DATA_URL = ${JSON.stringify(opts.dataURL)};

export interface ImageModelOptions {
  targetHeight?: number;
}

/**
 * Builds a 3D model from an image by extruding its silhouette.
 * The actual contour/extrude is produced by the img2threejs pipeline;
 * this factory wires the extracted average color + roughness + photo texture
 * to the generated geometry.
 */
export function createImageModel(opts: ImageModelOptions = {}) {
  const targetHeight = opts.targetHeight ?? 2.4;

  const texture = new THREE.TextureLoader().load(IMAGE_DATA_URL);
  texture.colorSpace = THREE.SRGBColorSpace;
  texture.anisotropy = 8;

  const capMat = new THREE.MeshStandardMaterial({
    map: texture,
    roughness: ${opts.roughness},
    metalness: 0.04,
  });
  const wallMat = new THREE.MeshStandardMaterial({
    color: new THREE.Color(${c[0]} / 255, ${c[1]} / 255, ${c[2]} / 255),
    roughness: ${opts.roughness},
    metalness: 0.04,
  });

  const group = new THREE.Group();
  return { group, capMat, wallMat, texture, targetHeight };
}
`;
}

/** Export a mesh as a binary GLB and trigger a download. */
export function exportGLB(mesh: THREE.Object3D, filename: string) {
  const exporter = new GLTFExporter();
  exporter.parse(
    mesh,
    (result) => {
      const blob = new Blob([result as ArrayBuffer], { type: 'model/gltf-binary' });
      triggerDownload(blob, filename);
    },
    (err) => console.error('GLB export failed', err),
    { binary: true }
  );
}

export function triggerDownload(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

export function downloadText(text: string, filename: string, mime = 'text/plain') {
  triggerDownload(new Blob([text], { type: mime }), filename);
}
